baseURL = "https://selfsealingstembolts.com/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Josh Weston"
copyright = "Copyright 2023-2024 Josh Weston"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "gruvbox"
    tabWidth = 4

[params]
subtitle = "For the love of infrastructure, automation, and yamok sauce."
enableGitalk = false
enableGiscus = false

# Microsoft Clarity (https://clarity.microsoft.com/) is a free user behavior recording and analytics tool
# clarity = "abcdefghzd"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Self-Sealing Stem Bolts" # will set 'og:site_name'
description = "A blog by Josh Weston"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

# [params.utterances]
# repo="your repo"
# term="[ENTER TERM HERE]"
# label="your label"
# theme="github-light"

[[menu.main]]
url = "/categories"
name = "Categories"
weight = 2
[[menu.main]]
url = "/tags"
name = "Tags"
weight = 3
[[menu.main]]
url = "/posts"
name = "Archive"
weight = 1
[[menu.main]]
url = "/index.xml"
name = "RSS Feed"
weight = 4
